package by.urbel.task03.controller.command;

public enum CommandName {
    AUTHORIZE,
    REGISTER,
    LOGOUT,
    GET_ALL_PRODUCTS,
    GET_PRODUCTS_IN_STOCK,
    GET_CART,
    GET_PRODUCT,
    CREATE_PRODUCT,
    DELETE_PRODUCT,
    CHANGE_PRODUCT_QUANTITY,
    ADD_PRODUCT_TO_CART,
    DELETE_PRODUCT_FROM_CART,
    GET_ALL_CATEGORIES,
    DELETE_CATEGORY,
    UPDATE_CATEGORY,
    CREATE_CATEGORY,
    CREATE_ORDER,
    GET_ORDERS_BY_STATUS,
    CHANGE_ORDER_STATUS,
    CREATE_ADMIN,
    GET_ALL_USERS,
    DELETE_USER
}
